#! /bin/sh

name=rust
version=1.89.0
git_url="https://github.com/rust-lang/rust.git"
commit=29483883eed69d5fb4db01964cdf2af4d86e9cb2
deps="rust-libc"

early_prepare() {
    git submodule update --init --recursive --depth=1
}
