#! /bin/sh

name=acl
version=2.3.2
revision=1
tarball_url="https://download.savannah.gnu.org/releases/acl/acl-${version}.tar.xz"
tarball_blake2b="9f2abfddcd403df2c716c05f02a1b52453613d10948dc58a65b9ef41b44e37db6de99fb22dcfc4f6f0fb5d0319c939da61bd4e0fba2cdb5643e8087ecd34eeac"
hostdeps="gcc pkg-config"
deps="core-libs attr"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
