#! /bin/sh

name=base-files
skip_pkg_check=yes
version=0.0
revision=1
source_dir="meta-sources/base-files"

package() {
    cp -r ${source_dir}/. "${dest_dir}"/
    install -dv -m 1777 "${dest_dir}"/tmp "${dest_dir}"/var/tmp
 
    chown -R 1000:1000 "${dest_dir}"/home/user

    chmod 750 "${dest_dir}"/root
    chmod 777 "${dest_dir}"/tmp
    chmod 777 "${dest_dir}"/run
    chmod 710 "${dest_dir}"/home/user
}
