#! /bin/sh

name=bootstrap-glib2
skip_pkg_check=yes
bootstrap_pkg=yes
from_source=glib2
revision=1
imagedeps="python3-docutils"
hostdeps="gcc pkg-config"
deps="core-libs pcre2 libffi zlib util-linux"

configure() {
    meson_configure \
        -Dglib_debug=disabled \
        -Dman-pages=enabled \
        -Dsysprof=disabled \
        -Dintrospection=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
