#! /bin/sh

name=colord
version=1.4.7
revision=1
tarball_url="https://www.freedesktop.org/software/colord/releases/colord-${version}.tar.xz"
tarball_blake2b="f4434ec817fc2afc1ade144f533d2c3b98117356677b5962ff95b566a8c66b6b8ce95ec8f76b3ae849a6468000dc08b8f8fc207c2cc9c85a966157fb1612078e"
imagedeps="build-essential meson ninja-build python3 patchelf colord itstool"
hostdeps="gcc pkg-config gobject-introspection glib vala"
deps="core-libs dbus glib lcms libgudev libgusb polkit sqlite"

configure() {
    vala_env meson_configure \
        -Dsystemd=true \
        -Dvapi=true \
        -Ddaemon_user=colord \
        -Dlibcolordcompat=true \
        -Dargyllcms_sensor=false \
        -Dbash_completion=false \
        -Ddocs=false \
        -Dman=false
}

build() {
    gi_env vala_env ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    mv -v ${dest_dir}${sysroot_dir}${prefix}/lib/* ${dest_dir}${prefix}/lib/

    post_package_strip
}
