#! /bin/sh

name=glib-gi
skip_pkg_check=yes
from_source=glib
revision=1
imagedeps="build-essential meson ninja-build python3-docutils python3 patchelf"
hostdeps="gcc pkg-config gobject-introspection glib"
deps="core-libs pcre2 libffi gobject-introspection"

configure() {
    meson_configure \
        -Dglib_debug=disabled \
        -Dman-pages=enabled \
        -Dsysprof=disabled \
        -Dintrospection=enabled
}

build() {
    gi_env ninja -j${parallelism}
}

package() {
    temp_dest_dir=$(mktemp -d)

    DESTDIR="${temp_dest_dir}" ninja install

    mkdir -p "${dest_dir}${prefix}/share/gir-1.0"
    mkdir -p "${dest_dir}${prefix}/lib/girepository-1.0"

    cp -rpv "${temp_dest_dir}${prefix}/share/gir-1.0/"* "${dest_dir}${prefix}/share/gir-1.0/"
    cp -rpv "${temp_dest_dir}${prefix}/lib/girepository-1.0/"* "${dest_dir}${prefix}/lib/girepository-1.0/"
}
