#! /bin/sh

name=gstreamer-plugins-base
repology_id=gstreamer:base
version=1.26.0
revision=1
tarball_url="https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-${version}.tar.xz"
tarball_blake2b="7d9bbbaf24d981af2794e013ece6b69b9e973ea34a1517bbb550b7d3d7ae778a676f56a56a07a67a684af458af53350f591fe1a1eff5f570d147f3a0374b35b6"
imagedeps="build-essential patchelf libwayland-bin"
hostdeps="gcc pkg-config gobject-introspection glib2"
deps="core-libs gstreamer alsa-lib graphene iso-codes libgudev libjpeg-turbo libogg libpng libtheora libvorbis libxi libxv mesa pango opus sdl2-compat gdk-pixbuf"

configure() {
    meson_configure \
        --wrap-mode=nodownload \
        -Dpackage-name="GStreamer ${version}" \
        -Dintrospection=enabled
}

build() {
    gi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
