#! /bin/sh

name=iptables
version=1.8.11
revision=1
tarball_url="https://www.netfilter.org/projects/iptables/files/iptables-${version}.tar.xz"
tarball_blake2b="82daca3940e253f6fda7cf5b3332488c31391ff66c0112c0cae2645ab61918f81e6028ea2b1e1385f21e4c5ff8cd64cba31072a2417a2ab696fe1c6b5464cea1"
source_hostdeps="autoconf automake libtool pkg-config"
hostdeps="gcc pkg-config"
deps="core-libs libpcap"

prepare() {
    autoreconf -fvi
}

configure() {
    autotools_configure \
        --disable-nftables \
        --enable-libipq
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
