#! /bin/sh

name=libadwaita
version=1.7.2
revision=1
tarball_url="https://download.gnome.org/sources/libadwaita/1.7/libadwaita-${version}.tar.xz"
tarball_blake2b="4cb583aaf87c95644b1fa3133463d13fc5acddcd056c7c97865c22540e9b998c43b739f3232c5a71de8245678967e7df14a8df35deb01cc844323f5993618e78"
imagedeps="build-essential patchelf sassc"
hostdeps="gcc pkg-config gobject-introspection glib2 vala"
deps="core-libs appstream gtk4 sassc"

configure() {
    vala_env meson_configure
}

build() {
    gi_env vala_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
