#! /bin/sh

name=libei
version=1.4.1
revision=1
tarball_url="https://gitlab.freedesktop.org/libinput/libei/-/archive/${version}/libei-${version}.tar.gz"
tarball_blake2b="2fd0d30b1853932d1b49a6cb0f564208e7e66232ace6cc3cefe0592fd0ed6f2741cc837d5189275046fd1484b1fdfd17e62f2f1275dbaee5a4f067d841892043"
imagedeps="python3-jinja2 python3-attr"
hostdeps="gcc pkg-config"
deps="core-libs libevdev libxkbcommon libxml2 systemd"

configure() {
    meson_configure \
        -Dtests=disabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
