#! /bin/sh

name=libical
version=3.0.20
revision=1
tarball_url="https://github.com/libical/libical/releases/download/v${version}/libical-${version}.tar.gz"
tarball_blake2b="3492efc8ace54b254a7079aa863394da0555a4c342b7c83a47991ecdf31fe06035bb8c196700ec6804bde2b1c074e5e3a2118c948fec26bdff90b92b9c5042e8"
source_hostdeps="glib"
# source_deps="autoconf-archive"
source_imagedeps="build-essential pkg-config cmake libxml2-dev libpcre2-dev libffi-dev"
imagedeps="cmake ninja-build build-essential python3 patchelf python3-distutils-extra pkg-config"
hostdeps="gcc pkg-config gobject-introspection glib vala"
# builddeps="base cmake ninja python gobject-introspection vala perl"
deps="core-libs icu glib-gi glib libxml pcre2"

prepare() {
	mkdir -p cross-build
    cd cross-build

    cmake \
        -DENABLE_GTK_DOC=OFF \
        ${source_dir}

    make -j${parallelism}
    cd ..
}

# TODO: Introspection support
configure() {
    ICAL_NATIVE_TOOL=${source_dir}/cross-build/bin/ical-glib-src-generator gi_env vala_env cmake_configure \
        -DSHARED_ONLY=yes \
        -DICAL_BUILD_DOCS=false \
        -DGOBJECT_INTROSPECTION=false \
        -DICAL_GLIB_VAPI=false \
        -DIMPORT_ICAL_GLIB_SRC_GENERATOR="${base_dir}"/build-support/libical/ical.cmake
}

build() {
    GI_SCANNER_DISABLE_CACHE=1 gi_env vala_env ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
