#! /bin/sh

name=libinput
version=1.28.1
revision=1
tarball_url="https://gitlab.freedesktop.org/libinput/libinput/-/archive/${version}/libinput-${version}.tar.gz"
tarball_blake2b="cf2cded91d031b123cc13e21d0961b6ae47e091650c10072f788476f1576269c67718a09d83beb7273101ef4ed6682519374cf46af81337491c3cc69648876b3"
hostdeps="gcc pkg-config"
deps="core-libs libevdev mtdev libwacom"

configure() {
    meson_configure \
        -Ddebug-gui=false \
        -Ddocumentation=false \
        -Dlibwacom=true \
        -Dtests=false \
        -Dudev-dir=${prefix}/lib/udev
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
