#! /bin/sh

name=libksba
version=1.6.7
revision=1
tarball_url="https://www.gnupg.org/ftp/gcrypt/libksba/libksba-${version}.tar.bz2"
tarball_blake2b="95f51bc9a0a7ee14b91089aded3a420cf2f986a1599e39e36dc46fd0b71bef465af9c6576c19516d0aadae67399eca69ae0448239216ba486812884ebefa1ae7"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs libgpg-error"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-libgpg-error-prefix=${sysroot_dir}${prefix}
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
