#! /bin/sh

name=libnotify
version=0.8.6
revision=1
tarball_url="https://download.gnome.org/sources/libnotify/0.8/libnotify-${version}.tar.xz"
tarball_blake2b="5598a3539deb9a08bdb03f4cad5efb1610f07c48fa6029657bcdbedb6a73966512fcc313d038a4f26c762fc0e26cb3e6c3aa9caa3e59f57fccf2f51adced6773"
imagedeps="build-essential patchelf"
hostdeps="gcc pkg-config glib2 gobject-introspection"
deps="core-libs gtk3"

configure() {
    meson_configure \
        -Dgtk_doc=false \
        -Dman=false
}

build() {
    gi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
