#! /bin/sh

name=libsecret
version=0.21.7
revision=1
tarball_url="https://download.gnome.org/sources/libsecret/0.21/libsecret-${version}.tar.xz"
tarball_blake2b="cf7571f69903178c6c2f45b8d24e576fdbf15b68024905934b0b8fcc2c16f826d569a9973d9d1592fabc40b668d0778076f882a93eba1dc5148289133c7b7e81"
imagedeps="build-essential patchelf"
hostdeps="gcc pkg-config gobject-introspection glib2 vala"
deps="core-libs glib2 libgcrypt"

configure() {
    vala_env meson_configure \
        -Dgtk_doc=false \
        -Dmanpage=false
}

build() {
    gi_env vala_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
