#! /bin/sh

name=libxtst
version=1.2.5
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libXtst-${version}.tar.xz"
tarball_blake2b="daf9d3c5412623a06c8579b341c1ab6e720719c4f3151acf5c735ea08c79c33800993d55cd9f9e8660be85e290fac641e5e9266deb4d317d9957ced847b1ebb1"
source_hostdeps="automake autoconf libtool pkg-config"
source_deps="xorg-util-macros"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs libxext libxfixes libxi xorg-util-macros xorg-proto"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
