#! /bin/sh

name=libxfce4ui
version=4.21.0
revision=1
tarball_url="https://archive.xfce.org/src/xfce/libxfce4ui/4.21/libxfce4ui-${version}.tar.xz"
tarball_blake2b="24b935f53cbcd80c7774319823b0fc916a6844953fe3d40d8f979157374494f84d38ec0e3e53863ebb5af208fa73ae33d465a9005e4e97cf43aa8436611892e0"
imagedeps="build-essential patchelf pkg-config python3 python3-distutils-extra xfce4-dev-tools"
hostdeps="gcc pkg-config glib2 gobject-introspection vala"
deps="core-libs libxfce4util gtk3 xfconf libsm startup-notification libgtop libepoxy hicolor-icon-theme libgudev"

configure() {
    vala_env meson_configure \
        -Dvendor-info="Jinix"
}

build() {
    gi_env vala_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
