#! /bin/sh

name=libyaml
version=0.2.5
revision=1
git_url="https://github.com/yaml/libyaml.git"
commit="2c891fc7a770e8ba2fec34fc6b545c672beb37e6"
imagedeps="cmake ninja-build"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
