#! /bin/sh

name=linux
version=6.14.4
revision=1
tarball_url="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${version}.tar.xz"
tarball_blake2b="8f5f44fa6f7b2a964a3fb14afd10dc0c6cc5ec73eb3b6dba24d35664f7083546b70eff7a3d5a9b3ba3c8b84785518c6df91aff0ed948cd538ff0b3b0484fd613"
revision=1
imagedeps="bc bison build-essential cpio dwarves flex kmod libelf-dev libncurses5-dev libssl-dev dracut busybox"
hostdeps="gcc"

build() {
    cp -rp "${source_dir}"/. ./

    cp "${base_dir}/build-support/linux-config" ./.config

    make \
        CROSS_COMPILE=${OS_TRIPLET}- \
        olddefconfig
    make -j${parallelism} \
        CROSS_COMPILE=${OS_TRIPLET}-
}

package() {
    mkdir -pv "${dest_dir}${prefix}"/share/linux

    cp -rpv arch/x86/boot/bzImage "${dest_dir}${prefix}"/share/linux/vmlinuz

    make \
        CROSS_COMPILE=${OS_TRIPLET}- \
        INSTALL_MOD_PATH="${dest_dir}${prefix}" \
        INSTALL_MOD_STRIP=1 \
        modules_install

    (
        until [ -f /tmp/dracut.*/initramfs/etc/shadow ]; do :; done
        chmod 644 /tmp/dracut.*/initramfs/etc/shadow
    ) &
    (
        until [ -f /tmp/dracut.*/initramfs/etc/gshadow ]; do :; done
        chmod 644 /tmp/dracut.*/initramfs/etc/gshadow
    ) &

    dracut \
        --verbose \
        --tmpdir /tmp \
        --kver ${version} \
        --kmoddir "${dest_dir}${prefix}"/lib/modules/${version} \
        --strip \
        --nomdadmconf \
        --nolvmconf \
        --no-hostonly \
        --add busybox \
        --omit systemd \
        "${dest_dir}${prefix}"/share/linux/initramfs
}
