#! /bin/sh

name=llvm
repology_id="llvm"
version=21.1.0
revision=1
tarball_url="https://github.com/llvm/llvm-project/releases/download/llvmorg-${version}/llvm-project-${version}.src.tar.xz"
tarball_blake2b="ac8c3cc8d2c986abcaa523acc872b01311ec118a738654f9cc53a1d5fdba70ba10cfe829e23f3913557e460403ed6a2df81cb5e9a435c8e1ce08e7ead3511bf0"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs ncurses zlib zstd libffi libxml2 binutils"

configure() {
        cmake_source_dir="${source_dir}/llvm" \
    cmake_configure \
        -UBUILD_SHARED_LIBS \
        -UENABLE_STATIC \
        -DLLVM_LINK_LLVM_DYLIB=ON \
        -DLLVM_ENABLE_FFI=ON \
        -DLLVM_ENABLE_EH=ON \
        -DLLVM_ENABLE_RTTI=ON \
        -DLLVM_DEFAULT_TARGET_TRIPLE=${OS_TRIPLET} \
        -DLLVM_HOST_TRIPLE=${OS_TRIPLET} \
        -DLLVM_BINUTILS_INCDIR=${sysroot_dir}${prefix}/include \
        -DLLVM_INCLUDE_BENCHMARKS=OFF \
        -DCLANG_DEFAULT_PIE_ON_LINUX=ON \
        -DCLANG_CONFIG_FILE_SYSTEM_DIR=/etc/clang \
        -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld" \
        -Wno-dev
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
