#! /bin/sh

name=mesa
version=25.2.1
revision=2
git_url="https://gitlab.freedesktop.org/mesa/mesa.git"
commit=d6e3b017b2e38131a4918624c9c3c2792f477a96
imagedeps="python3-mako python3-yaml glslang-tools libwayland-bin pkg-config"
hostdeps="gcc pkg-config"
deps="core-libs libdrm libexpat libglvnd libx11 libxcb libxext libxfixes libxrandr libxshmfence libxxf86vm llvm systemd wayland-protocols xcb-util-keysyms zlib zstd"

configure() {
    meson_configure \
        -Db_ndebug=true \
        -Dbuild-tests=false \
        -Dexpat=enabled \
        -Dgbm=enabled \
        -Dgles1=enabled \
        -Dgles2=enabled \
        -Dglvnd=enabled \
        -Degl=enabled \
        -Dllvm=enabled \
        -Dzstd=enabled \
        -Dvideo-codecs=all_free \
        -Dvulkan-drivers=amd,swrast,virtio \
        -Dvulkan-layers=device-select,intel-nullhw,overlay \
        -Dgallium-drivers=r300,r600,nouveau,virgl,svga,i915,crocus,zink,softpipe,llvmpipe \
        -Dgallium-extra-hud=true \
        -Dgallium-rusticl=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
