#! /bin/sh

name=mlibc
skip_pkg_check=yes
version=0.0git
revision=39
git_url="https://github.com/managarm/mlibc.git"
commit=1183d85f914f3c7cea56961edbf472b49b22d92b
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="linux-headers mlibc-headers"

early_prepare() {
    sed -i 's/^revision = .*/revision = 10c37771247545fe5afb4edc27edc39be47d9e56/g' subprojects/freestnd-c-hdrs.wrap
    sed -i 's/^revision = .*/revision = 6703c46226d574b29cf262b1a50f4a5ace0d53d0/g' subprojects/freestnd-cxx-hdrs.wrap
    sed -i 's/^revision = .*/revision = 5304639c1c9fd3713fd759453b0415b968dcaa06/g' subprojects/frigg.wrap

    meson subprojects download

    curl -Lo libgcc-x86_64.a https://github.com/osdev0/libgcc-binaries/releases/download/2025-08-21/libgcc-x86_64.a
    b2sum libgcc-x86_64.a | grep -q f41054803d2c8475ca394b37e4368aa7ae900bb73409f3d9566b4348797a16efadc97e28ed5db1432c30ba8c4b5ae8fb5ff42ec6d77c2f749765cac89bd66b56

    curl -Lo libgcc-riscv64.a https://github.com/osdev0/libgcc-binaries/releases/download/2025-08-21/libgcc-riscv64.a
    b2sum libgcc-riscv64.a | grep -q f0076a3e36f34fff8c7186e9379940747f009a73d71e88a9f33a29dd7d1993ae01d800187e86510249e7043c2ab24b07a2249f2a985a55af6e1a2fcdf029665b
}

configure() {
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS -Wl,${source_dir}/libgcc-${JINX_ARCH}.a" \
    meson_configure_noflags \
        -Dno_headers=true \
        -Ddefault_library=both \
        -Dlibgcc_dependency=false \
        -Duse_freestnd_hdrs=enabled \
        -Dlinux_kernel_headers="${sysroot_dir}${prefix}/include"
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}
