#! /bin/sh

name=mlibc-run-wrapper
skip_pkg_check=yes
version=0.0git
revision=1
source_dir="meta-sources/run-wrapper"
imagedeps="build-essential meson ninja-build"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
