#! /bin/sh

name=polkit
version=126
revision=1
tarball_url="https://github.com/polkit-org/polkit/archive/${version}/polkit-${version}.tar.gz"
tarball_blake2b="2e86c8853edf29879d8367b77d210d3a891178297cb5f9eb204a953bfaa66f6ff2307da265f4c3f89265ba8ce32e94641272d654a78d116dfb32a65d402f877a"
imagedeps="build-essential patchelf pkg-config"
hostdeps="gcc pkg-config gobject-introspection glib2 vala"
deps="core-libs duktape glib2 libxslt pam systemd"

configure() {
    vala_env meson_configure \
        -Dman=false \
        -Dtests=false \
        -Dintrospection=true \
        -Dsession_tracking=logind \
        -Dos_type=lfs \
        -Dsystemdsystemunitdir=${prefix}/lib/systemd/system \
        -Dsysusers_dir=${prefix}/lib/sysusers.d \
        -Dtmpfiles_dir=${prefix}/lib/tmpfiles.d
}

build() {
    gi_env vala_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
