#! /bin/sh

name=shadow
version=4.17.4
revision=1
tarball_url="https://github.com/shadow-maint/shadow/releases/download/${version}/shadow-${version}.tar.xz"
tarball_blake2b="591e16e50cbba4e8b065f62d548bd8515192b479d1b73f464be315a2cbbab3ebdae132b9e087c98c11d125ac478dada5c3bc6f2637cc1ba91c6f7fe49c74d80e"
hostdeps="gcc pkg-config"
deps="core-libs pam attr acl"

prepare() {
    autotools_recursive_regen
}

configure() {
    cp -rp "${source_dir}"/. ./

    sed -i 's/groups$(EXEEXT) //' ./src/Makefile.in
    sed -i 's/groups\.1 / /' ./man/Makefile.in
    sed -i 's/getspnam\.3 / /' ./man/Makefile.in
    sed -i 's/passwd\.5 / /' ./man/Makefile.in

    sed -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD YESCRYPT@' \
    -e 's@/var/spool/mail@/var/mail@'                   \
    -e '/PATH=/{s@/sbin:@@;s@/bin:@@}'                  \
    -i ./etc/login.defs

        LIBS="-lintl" \
        configure_script_path=./configure \
    autotools_configure \
        --with-bcrypt \
        --with-yescrypt \
        --without-libbsd \
        --with-group-name-max-length=32 \
        --disable-shadowgrp # Disabled due to mlibc missing endsgent and friends
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make exec_prefix=${prefix} pamddir= install
    DESTDIR="${dest_dir}" make -C man install-man

    # --sbindir does not seem to work
    mv -v ${dest_dir}${prefix}/sbin/* ${dest_dir}${prefix}/bin/
    rm -rvf ${dest_dir}${prefix}/sbin

    install -v -m644 ${dest_dir}/etc/login.defs ${dest_dir}/etc/login.defs.orig

    for FUNCTION in FAIL_DELAY               \
                FAILLOG_ENAB             \
                LASTLOG_ENAB             \
                MAIL_CHECK_ENAB          \
                OBSCURE_CHECKS_ENAB      \
                PORTTIME_CHECKS_ENAB     \
                QUOTAS_ENAB              \
                CONSOLE MOTD_FILE        \
                FTMP_FILE NOLOGINS_FILE  \
                ENV_HZ PASS_MIN_LEN      \
                SU_WHEEL_ONLY            \
                PASS_CHANGE_TRIES        \
                PASS_ALWAYS_WARN         \
                CHFN_AUTH ENCRYPT_METHOD \
                ENVIRON_FILE
    do
        sed -i "s/^${FUNCTION}/# &/" ${dest_dir}/etc/login.defs
    done

    [ -f ${dest_dir}/etc/login.access ] && mv -v ${dest_dir}/etc/login.access
    [ -f ${dest_dir}/etc/login.access ] && mv -v ${dest_dir}/etc/login.access.NOUSE
    [ -f ${dest_dir}/etc/limits ] && mv -v ${dest_dir}/etc/limits
    [ -f ${dest_dir}/etc/limits ] && mv -v ${dest_dir}/etc/limits.NOUSE

    mkdir -pv ${dest_dir}/etc/pam.d/
    cp -v "${base_dir}"/build-support/shadow/* "${dest_dir}"/etc/pam.d/

    post_package_strip
}
