#! /bin/sh

name=totem-pl-parser
version=3.26.6
revision=1
tarball_url="https://download.gnome.org/sources/totem-pl-parser/3.26/totem-pl-parser-${version}.tar.xz"
tarball_blake2b="b0768f54c77ff902ad20aeaa9162c616e0cc64ccfc2839d2db2e4c9076f82a611baedf127b0b74f84ec8698a5adc25c43fb9245dcb26a221da7024372a61896b"
imagedeps="build-essential patchelf"
hostdeps="gcc pkg-config gobject-introspection glib2"
deps="core-libs libarchive libgcrypt glib2"

configure() {
    meson_configure
}

build() {
    gi_env meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
