#! /bin/sh

name=vte
version=0.80.3
revision=3
git_url="https://gitlab.gnome.org/GNOME/vte.git"
commit=02eaf1997d904dbfb792e2ae9ae0ba8b82f117f1
imagedeps="build-essential patchelf"
hostdeps="gcc pkg-config gobject-introspection glib2 vala"
deps="core-libs fast_float cairo fribidi glib2 gnutls gtk3 gtk4 icu pango pcre2 zlib fast_float"

configure() {
    vala_env meson_configure \
        -Da11y=true \
        -Dfribidi=true \
        -Dglade=true \
        -Dgnutls=true \
        -Dgtk3=true \
        -Dgtk4=true \
        -Dicu=true \
        -Dgir=true \
        -Dvapi=true \
        -D_systemd=true
}

build() {
    gi_env vala_env meson compile -j${parallelism}
}

package() {
    DESTDIR=${dest_dir} meson install --no-rebuild

    rm -vr ${dest_dir}/etc/

    post_package_strip
}
