#! /bin/sh

name=webp-pixbuf-loader
version=0.2.7
revision=1
tarball_url="https://github.com/aruiz/webp-pixbuf-loader/archive/${version}/webp-pixbuf-loader-${version}.tar.gz"
tarball_blake2b="7f81addbe268aab79c83f587bb26ac4d2ba8311da49d6e0b690003256e8e5206523aabc2dcb0bf6da38267872f24a6daeff0f5062a77e8e60c08610f3ee0ede7"
imagedeps="meson ninja-build"
hostdeps="gcc pkg-config"
deps="core-libs libwebp gdk-pixbuf"

configure() {
    meson_configure
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    # The pixbuf loader is installed in the wrong directory, move it
    mkdir -pv ${dest_dir}${prefix}/lib/gdk-pixbuf-2.0/2.10.0/loaders/
    mv -v ${dest_dir}${sysroot_dir}${prefix}/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-webp.so ${dest_dir}${prefix}/lib/gdk-pixbuf-2.0/2.10.0/loaders/

    post_package_strip
}
