#! /bin/sh

name=wpa-supplicant
version=2.11
revision=1
tarball_url="https://w1.fi/releases/wpa_supplicant-${version}.tar.gz"
tarball_blake2b="71bd0d11cd31eb5bc6beb51caf0f1399856ea188f316d2330053a2d8c81869057811e9f500828e8981eabd0af38f30a18a3ae584d744005c78681c82fa910abf"
hostdeps="gcc pkg-config"
deps="core-libs libnl libxml2 dbus"

prepare() {
    cat > wpa_supplicant/.config <<EOF
CONFIG_BACKEND=file
CONFIG_CTRL_IFACE=y
CONFIG_DEBUG_FILE=y
CONFIG_DEBUG_SYSLOG=y
CONFIG_DEBUG_SYSLOG_FACILITY=LOG_DAEMON
CONFIG_DRIVER_NL80211=y
CONFIG_DRIVER_WEXT=y
CONFIG_DRIVER_WIRED=y
CONFIG_EAP_GTC=y
CONFIG_EAP_LEAP=y
CONFIG_EAP_MD5=y
CONFIG_EAP_MSCHAPV2=y
CONFIG_EAP_OTP=y
CONFIG_EAP_PEAP=y
CONFIG_EAP_TLS=y
CONFIG_EAP_TTLS=y
CONFIG_IEEE8021X_EAPOL=y
CONFIG_IPV6=y
CONFIG_LIBNL32=y
CONFIG_PEERKEY=y
CONFIG_PKCS12=y
CONFIG_READLINE=y
CONFIG_SMARTCARD=y
CONFIG_WPS=y
CONFIG_CTRL_IFACE_DBUS=y
CONFIG_CTRL_IFACE_DBUS_NEW=y
CONFIG_CTRL_IFACE_DBUS_INTRO=y
CFLAGS += -I${sysroot_dir}${prefix}/include/libnl3
EOF
}

build() {
    cp -rp ${source_dir}/. ./
    make -C wpa_supplicant CC=${OS_TRIPLET}-gcc PKG_CONFIG=${OS_TRIPLET}-pkg-config BINDIR=${prefix}/bin LIBDIR=${prefix}/lib -j${parallelism}
}

package() {
    cd wpa_supplicant

    mkdir -pv ${dest_dir}${prefix}/bin
    mkdir -pv ${dest_dir}${prefix}/share/man/man5
    mkdir -pv ${dest_dir}${prefix}/share/man/man8
    mkdir -pv ${dest_dir}${prefix}/share/dbus-1/system-services
    mkdir -pv ${dest_dir}/etc/dbus-1/system.d

    install -v -m755 wpa_cli ${dest_dir}${prefix}/bin/
    install -v -m755 wpa_passphrase ${dest_dir}${prefix}/bin/
    install -v -m755 wpa_supplicant ${dest_dir}${prefix}/bin/
    install -v -m644 doc/docbook/wpa_supplicant.conf.5 ${dest_dir}${prefix}/share/man/man5/
    install -v -m644 doc/docbook/wpa_cli.8 ${dest_dir}${prefix}/share/man/man8/
    install -v -m644 doc/docbook/wpa_passphrase.8 ${dest_dir}${prefix}/share/man/man8/
    install -v -m644 doc/docbook/wpa_supplicant.8 ${dest_dir}${prefix}/share/man/man8/

    mkdir -pv ${dest_dir}${prefix}/lib/systemd/system
    install -v -m644 systemd/*.service ${dest_dir}${prefix}/lib/systemd/system/

    install -v -m644 dbus/fi.w1.wpa_supplicant1.service ${dest_dir}${prefix}/share/dbus-1/system-services/
    install -v -m644 dbus/dbus-wpa_supplicant.conf ${dest_dir}/etc/dbus-1/system.d/wpa_supplicant.conf

    post_package_strip
}
