#! /bin/sh

name=xbps
version=0.60.5
revision=3
tarball_url="https://github.com/void-linux/xbps/archive/refs/tags/${version}.tar.gz"
tarball_blake2b="91aad926f25e78c17b2646f2e478e9a4141d9d80ebb93bc821c91333c8f5b5cf72a08edb7f25aef486e0761f15da8322207474c3b6f546d6403dd424cc442525"
hostdeps="gcc pkg-config"
deps="core-libs libarchive openssl zlib"

configure() {
    cp -rp "${source_dir}"/. ./

        CFLAGS="$TARGET_CFLAGS -Wno-error" \
        LDFLAGS="$TARGET_LDFLAGS" \
    ./configure \
        --verbose \
        --host=${OS_TRIPLET} \
        --prefix="${prefix}" \
        --sysconfdir=/etc
}

build() {
    make -j${parallelism} \
        AR="${OS_TRIPLET}-ar" \
        RANLIB="${OS_TRIPLET}-ranlib"
}

package() {
    DESTDIR="${dest_dir}" make install

    # Remove static libraries
    rm "${dest_dir}${prefix}"/lib/*.a
    # Install a systemd service file
    mkdir -p "${dest_dir}${prefix}"/lib/systemd/system
    cat > "${dest_dir}${prefix}"/lib/systemd/system/xbps-reconfigure.service <<EOF
[Unit]
Description=Reconfigure xbps packages

[Service]
ExecStart=${prefix}/bin/xbps-reconfigure -a

[Install]
WantedBy=basic.target
EOF
    # Mark the service as enabled
    mkdir -pv ${dest_dir}/etc/systemd/system/basic.target.wants
    ln -sv "${prefix}"/lib/systemd/system/xbps-reconfigure.service \
        "${dest_dir}"/etc/systemd/system/basic.target.wants/xbps-reconfigure.service

    post_package_strip
}
