#! /bin/sh

name=xcb-util-renderutil
version=0.3.10
revision=1
tarball_url="https://xcb.freedesktop.org/dist/xcb-util-renderutil-${version}.tar.xz"
tarball_blake2b="49b017fed34cd1c8cceae697bf76dc17c34c32dcc05acaff87c75f74fcd486bc0abc9fe4699cc989c1afd13ac33fc04092719209e9d48aceb5e35d64a5790393"
hostdeps="gcc pkg-config"
deps="core-libs libxcb xcb-util"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
