#! /bin/sh

name=xorg-server
version=21.1.18
revision=1
tarball_url="https://www.x.org/releases/individual/xserver/xorg-server-${version}.tar.xz"
tarball_blake2b="48c7b745c07a31d11d3a95f8eba056ff46bf69f2c70d499f677cbd706347e0c3c28a8197be5c0d65670c5b2f87f559ea10e7c21ee88bdc767c6a921d5fa8d3b2"
hostdeps="gcc pkg-config"
deps="core-libs dbus xorg-util-macros xorg-proto xcb-proto xtrans libtirpc libdrm libpciaccess libxinerama libxcvt libxshmfence libx11 libxaw libxxf86vm libxkbfile libxmu libxfont2 libepoxy libxi libxv libxdamage libxrender libxrandr libxcb libxfixes libxext nettle mesa xorg-font-util xorg-xkbcomp xkeyboard-config pixman"

configure() {
    meson_configure \
        -Dglamor=true \
        -Dsystemd_logind=true \
        -Dxkb_dir=${prefix}/share/X11/xkb \
        -Dxkb_output_dir=/var/lib/xkb \
        -Dxkb_bin_dir=${prefix}/bin \
        -Ddefault_font_path=${prefix}/share/fonts/X11/misc

    sed -i 's|/sysroot||' include/dix-config.h
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
