#! /bin/sh

# Basic script that naively mimicks ldd, required for g-ir-scanner

# Unset LD_LIBRARY_PATH to avoid loading target libraries when running host tools.
unset LD_LIBRARY_PATH

${OBJDUMP} -p $1 | awk '/NEEDED/{print $2" => /usr/lib/"$2}'
