#! /bin/sh

name=gobject-introspection
revision=1
from_source="gobject-introspection"
imagedeps="build-essential libpython3-dev pkg-config libpcre2-dev libffi-dev"
hostdeps="gcc glib2"

configure() {
    meson setup "${source_dir}" \
        --prefix=${prefix} \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --libdir=lib \
        --sbindir=bin \
        --buildtype=release \
        -Ddefault_library=shared \
        -Dgtk_doc=false \
        -Dbuild_introspection_data=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    strip_command=strip \
        post_package_strip
}
