#! /bin/sh

name=libical
from_source=libical
revision=1
hostdeps="glib2"
imagedeps="build-essential pkg-config libxml2-dev libpcre2-dev libffi-dev"

configure() {
    cmake \
        -DENABLE_GTK_DOC=OFF \
        -DCMAKE_INSTALL_PREFIX="${prefix}" \
        -DCMAKE_BUILD_TYPE=Release \
        ${source_dir}
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

        strip_command=strip \
    post_package_strip
}
