#! /bin/sh

name=llvm
from_source=llvm
revision=1
imagedeps="build-essential"
hostrundeps="binutils"

configure() {
    cmake \
        -GNinja \
        -DCMAKE_INSTALL_PREFIX="${prefix}" \
        -DCMAKE_BUILD_TYPE=Release \
        -DLLVM_LINK_LLVM_DYLIB=ON \
        -DLLVM_TARGETS_TO_BUILD=X86 \
        -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld" \
        -DDEFAULT_SYSROOT="${sysroot_dir}" \
        ${source_dir}/llvm
}

build() {
    cmake --build . -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

        strip_command=strip \
    post_package_strip
}
