#! /bin/sh

name=vala
revision=1
from_source=vala
# imagedeps="python3-docutils build-essential libpcre2-dev pkg-config libffi-dev zlib1g-dev"
imagedeps="build-essential pkg-config libpcre2-dev pkg-config libffi-dev zlib1g-dev"
hostdeps="glib2 gobject-introspection"

prepare() {
    autotools_recursive_regen
}

configure() {
        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
    "${source_dir}"/configure \
        --prefix="${prefix}" \
        --disable-valadoc
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    strip_command=strip \
        post_package_strip
}
